from tkinter import *
from tkinter import ttk
import random as rd

dummy = "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of de Finibus Bonorum et Malorum (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, Lorem ipsum dolor sit amet.., comes from a line in section 1.10.32.\
            The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from de Finibus Bonorum et Malorum by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.\
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."

# user guesses the number generated by computer
def guess_me():
    from_num = int(input("from: "))
    to_num = int(input("to: "))

    num = rd.randint(from_num, to_num)
    print("Number for guessing is generated! Now please guess.")

    # do-while emulate:
    while True:
        user_guess = int(input(f"Guess the number between {from_num} and {to_num}: "))

        if user_guess < num:
            print('This is too low. Guess again.')
        elif user_guess > num:
            print('This is too high. Guess again.')
        else:
            print('Congrats!!!! You got it!')
            break

# computer guesses the number generated by user
def let_me_guess():
    low_bound = 1
    high_bound = int(input("high bound: "))

    while True:
        if low_bound != high_bound:
            computer_guess = rd.randint(low_bound, high_bound)
        else:
            computer_guess = low_bound

        answer = input(f'{computer_guess} is too low, or too high, or it is the correct number you are thinking of?').lower()
        if answer in ['l', 'low']:
            low_bound = computer_guess
        elif answer in ['h', 'high']:
            high_bound = computer_guess
        else:
            print('Congrats!!!! Computer, you got it!')
            break

class MainFrame():
    def __init__(self, parent):
        parent.title("GAME: Random number.")

        # main frame components
        frame = Frame(parent)
        self._row = 0

        self.label = Label(frame, text='Welcome to the game of the century')

        self.nb = ttk.Notebook(frame)
        self.pn1 = Frame(self.nb)
        self.pn2 = Frame(self.nb)

        self.nb.add(self.pn1, text='Guess me!')
        self.nb.add(self.pn2, text='Let me guess!')

        self.btnExit = Button(frame, text='Exit')

        # main frame layout
        frame.grid(row=0, column=0, sticky='nw')
        frame.grid_columnconfigure(0, weight = 1)
        frame.grid_rowconfigure(0, weight = 1)

        self.label.grid(row=self._row, column=0)
        self.nb.grid(row=self._irow(), column=0, padx=10)
        self.btnExit.grid(row=self._irow(), column=0, sticky='e')


        # panel 1: user guesses the computer-generated number.
        pn1_frame0 = Frame(self.pn1)
        pn1_frame1 = Frame(self.pn1)
        pn1_frame2 = Frame(self.pn1)

        self.pn1_label0 = Label(pn1_frame0, text='Provide a range so that the program can choose a number for you.')
        
        self.pn1_label1 = Label(pn1_frame1, text='From: ')
        self.from_num = Entry(pn1_frame1)
        self.pn1_label2 = Label(pn1_frame1, text='To: ')
        self.to_num = Entry(pn1_frame1)

        self.scrollbar = Scrollbar(pn1_frame2)
        self.pn1_text = Text(pn1_frame2, yscrollcommand=self.scrollbar.set)
        self.pn1_text.insert(END, dummy*2)

        # panel 1: layout
        pn1_frame0.grid(row=0, column=0, sticky='w')
        pn1_frame1.grid(row=1, column=0, sticky='w')
        pn1_frame2.grid(row=2, column=0, sticky='w')

        self.pn1_label0.grid(row=0, column=0)
        self.pn1_label1.grid(row=0, column=0, sticky='e')
        self.from_num.grid(row=0, column=1)
        self.pn1_label2.grid(row=1, column=0, sticky='e')
        self.to_num.grid(row=1, column=1)
        self.scrollbar.pack(side=RIGHT, fill=Y)
        self.pn1_text.pack(side=LEFT, fill=BOTH, expand=1)


        # panel 2: computer guesses the user-generated number
        pn2_frame0 = Frame(self.pn2)
        pn2_frame1 = Frame(self.pn2)

        self.pn2_label0 = Label(pn2_frame0, text='Provide a high bound so the program knows where to start off with.')
        self.pn2_label1 = Label(pn2_frame1, text='Upper bound: ')
        self.upper_bound = Entry(pn2_frame1)

        # panel 2: layout
        pn2_frame0.grid(row=0, column=0, sticky='w')
        pn2_frame1.grid(row=1, column=0, sticky='w')

        self.pn2_label0.grid(row=0, column=0)
        self.pn2_label1.grid(row=0, column=0)
        self.upper_bound.grid(row=0, column=1)


    def _irow(self):
        self._row = self._row + 1
        return self._row




def main():
    app = Tk()
    MainFrame(app)
    # app.geometry('750x250+400+300') 
    app.state('zoomed') # maximize GUI
    app.mainloop()

    # guess_me()
    # print('====================================')
    # let_me_guess()

if __name__ == '__main__':
    main()
