from tkinter import *
from tkinter import ttk
import random as rd


# user guesses the number generated by computer
def guess_me():
    print("Provide a range so that the program can choose a number for you")
    from_num = int(input("from: "))
    to_num = int(input("to: "))

    num = rd.randint(from_num, to_num)
    print("Number for guessing is generated! Now please guess.")

    # do-while emulate:
    while True:
        user_guess = int(input(f"Guess the number between {from_num} and {to_num}: "))

        if user_guess < num:
            print('This is too low. Guess again.')
        elif user_guess > num:
            print('This is too high. Guess again.')
        else:
            print('Congrats!!!! You got it!')
            break

# computer guesses the number generated by user
def let_me_guess():
    print("Provide a high bound so the program knows where to start off with.")
    low_bound = 1
    high_bound = int(input("high bound: "))

    while True:
        if low_bound != high_bound:
            computer_guess = rd.randint(low_bound, high_bound)
        else:
            computer_guess = low_bound

        answer = input(f'{computer_guess} is too low, or too high, or it is the correct number you are thinking of?').lower()
        if answer in ['l', 'low']:
            low_bound = computer_guess
        elif answer in ['h', 'high']:
            high_bound = computer_guess
        else:
            print('Congrats!!!! Computer, you got it!')
            break

class MainFrame():
    def __init__(self, parent):
        parent.title("Random number.")
        frame = ttk.Frame(parent)
        frame.grid(column=0, row=0, sticky=(N, W, E, S))

        # main frame components:
        self.label1 = ttk.Label(frame, text='Welcome to "Guess me" game\n')
        self.btn = ttk.Button(parent, text='Exit')

        self.nb = ttk.Notebook(frame)
        self.pn1 = ttk.Frame(self.nb)
        self.pn2 = ttk.Frame(self.nb)

        self.nb.add(self.pn1, text='Guess me!')
        self.nb.add(self.pn2, text='Let me guess!')

        


        # layout
        self.label1.pack(fill='both', side='top')
        self.nb.pack(fill ="both", expand = True)

        self.btn.grid(column=1, row=1, sticky=(S,E))

def main():
    app = Tk()
    MainFrame(app)
    # app.geometry('750x250+400+300') 
    app.state('zoomed') # maximize GUI
    app.mainloop()

    # guess_me()
    # print('====================================')
    # let_me_guess()

if __name__ == '__main__':
    main()
