from tkinter import *
from tkinter import ttk
from tkinter import messagebox
import random as rd

PAD = 10


class MainFrame():
    def __init__(self, parent):
        parent.title("GAME: Random number.")

        # main frame components
        frame = Frame(parent)
        self._row = 0

        self.label = Label(frame, text='Welcome to the game of the century')

        self.nb = ttk.Notebook(frame)
        self.pn1 = Frame(self.nb)
        self.pn2 = Frame(self.nb)

        self.nb.add(self.pn1, text='Guess me!')
        self.nb.add(self.pn2, text='Let me guess!')

        self.btnExit = Button(frame, text='EXIT', command=parent.quit, padx=PAD)

        # main frame layout
        frame.grid(row=0, column=0, sticky='nw')
        frame.columnconfigure(0, weight=1)

        self.label.grid(row=self._row, column=0)
        self.nb.grid(row=self._irow(), column=0, padx=PAD)
        self.btnExit.grid(row=self._irow(), column=0, sticky='e', pady=PAD, padx=PAD)


        # panel 1: user guesses the computer-generated number.
        pn1_frame0 = Frame(self.pn1)    # text
        pn1_frame1 = Frame(self.pn1)    # inputs
        pn1_frame2 = Frame(self.pn1)    # log

        self.pn1_label0 = Label(pn1_frame0, text='Provide a range so that the program can choose a number for you.')
        
        self.pn1_label1 = Label(pn1_frame1, text='From: ')
        self.from_num = Entry(pn1_frame1)
        self.pn1_label2 = Label(pn1_frame1, text='To: ')
        self.to_num = Entry(pn1_frame1)
        self.pn1_btnGenerate = Button(pn1_frame1, text='GENERATE', padx=PAD)

        self.pn1_scrollbar = Scrollbar(pn1_frame2)
        self.pn1_text = Text(pn1_frame2, yscrollcommand=self.pn1_scrollbar.set)

        self.pn1_label3 = Label(pn1_frame2, text='Answer: ')
        self.pn1_answer = Entry(pn1_frame2)
        self.pn1_btnCheck = Button(pn1_frame2, text='CHECK', padx=PAD)

        # btn binding
        self.pn1_btnGenerate.bind('<ButtonRelease-1>', self.onGenerate)
        self.pn1_btnCheck.bind('<ButtonRelease-1>', self.onPn1_Check)


        # panel 1: layout
        pn1_frame0.grid(row=0, column=0, sticky='w', pady=PAD)
        pn1_frame1.grid(row=1, column=0, sticky='w', pady=PAD)
        pn1_frame2.grid(row=2, column=0, sticky='w', pady=PAD)

        self.pn1_label0.grid(row=0, column=0)
        self.pn1_label1.grid(row=0, column=0, sticky='e')
        self.from_num.grid(row=0, column=1)
        self.pn1_label2.grid(row=1, column=0, sticky='e')
        self.to_num.grid(row=1, column=1)
        self.pn1_btnGenerate.grid(row=1, column=2, padx=PAD)

        self.pn1_text.pack(side=LEFT, fill=BOTH, expand=1)
        self.pn1_scrollbar.pack(side=LEFT, fill=Y)
        self.pn1_label3.pack(side=TOP, padx=PAD)
        self.pn1_answer.pack(side=TOP, padx=PAD)
        self.pn1_btnCheck.pack(side=TOP, pady=PAD)


        # panel 2: computer guesses the user-generated number
        pn2_frame0 = Frame(self.pn2)    # text
        pn2_frame1 = Frame(self.pn2)    # inputs
        pn2_frame2 = Frame(self.pn2)    # log

        self.pn2_label0 = Label(pn2_frame0, text='Provide a high bound so the program knows where to start off with.')
        self.pn2_label1 = Label(pn2_frame1, text='Upper bound: ')
        self.upper_bound = Entry(pn2_frame1)
        self.pn2_btnFirstGuess = Button(pn2_frame1, text='FIRST GUESS', padx=PAD)

        self.pn2_scrollbar = Scrollbar(pn2_frame2)
        self.pn2_text = Text(pn2_frame2, yscrollcommand=self.pn2_scrollbar.set)

        self.pn2_label3 = Label(pn2_frame2, text='Answer: ')
        self.pn2_answer = Entry(pn2_frame2)
        self.pn2_btnCheck = Button(pn2_frame2, text='CHECK', padx=PAD)

        # btn binding
        self.pn2_btnCheck.bind('<ButtonRelease-1>', self.onPn2_Check)
        self.pn2_btnFirstGuess.bind('<ButtonRelease-1>', self.onPn2_FirstFuess)

        # panel 2: layout
        pn2_frame0.grid(row=0, column=0, sticky='w', pady=PAD)
        pn2_frame1.grid(row=1, column=0, sticky='w', pady=PAD)
        pn2_frame2.grid(row=2, column=0, sticky='w', pady=PAD)

        self.pn2_label0.grid(row=0, column=0)
        self.pn2_label1.grid(row=0, column=0, sticky='e')
        self.upper_bound.grid(row=0, column=1)
        self.pn2_btnFirstGuess.grid(row=0, column=2, padx=PAD)

        self.pn2_text.pack(side=LEFT, fill=BOTH, expand=1)
        self.pn2_scrollbar.pack(side=LEFT, fill=Y)
        self.pn2_label3.pack(side=TOP, padx=PAD)
        self.pn2_answer.pack(side=TOP, padx=PAD)
        self.pn2_btnCheck.pack(side=TOP, pady=PAD)


    def _irow(self):
        self._row = self._row + 1
        return self._row

    def onGenerate(self, evt):
        self.pn1_varCheck()

        self.num = rd.randint(int(self.from_num.get()), int(self.to_num.get()))
        self.pn1_text.insert(END, 'Number for guessing is generated! Now please guess.\n')

    # user guesses the number generated by computer
    def onPn1_Check(self, evt):
        self.pn1_varCheck()

        if self.pn1_answer.get():
            user_guess = int(self.pn1_answer.get())
        else:
            messagebox.showwarning('Warning', 'No answer provided.')

        if user_guess < self.num:
            self.pn1_text.insert(END, 'This is too low. Guess again.\n')
        elif user_guess > self.num:
            self.pn1_text.insert(END, 'This is too high. Guess again.\n')
        else:
            self.pn1_text.insert(END, 'Congrats!!!! You got it!\n')

    def onPn2_FirstFuess(self, evt):
        self.pn2_varCheck()

        self.low_bound = 1
        self.high_bound = int(self.upper_bound.get())
 
        if self.low_bound != self.high_bound:
            self.computer_guess = rd.randint(self.low_bound, self.high_bound)
        else:
            self.pn2_text.insert(END, 'Congrats!!!! Computer, you just happen to know which number I am thinking!')

        self.pn2_text.insert(END, f'{self.computer_guess} is too low, or too high, or it is the correct number you are thinking of?\n')

        return

    # computer guesses the number generated by user
    def onPn2_Check(self, evt):
        self.pn2_varCheck()

        if self.pn2_answer.get():
            answer = self.pn2_answer.get().lower()
        else:
            messagebox.showwarning('Warning', 'No answer provided.')

        if self.low_bound != self.high_bound:
            self.computer_guess = rd.randint(self.low_bound, self.high_bound)

            if answer in ['l', 'low']:
                self.low_bound = self.computer_guess
            elif answer in ['h', 'high']:
                self.high_bound = self.computer_guess
            elif answer in ['c','correct']:
                self.pn2_text.insert(END, 'Congrats!!!! Computer, you got it!\n')
                return
            else:
                messagebox.showwarning('Warning','Wrong input. \nAcceptable inputs: c, correct, l, low, h, high')

            self.pn2_text.insert(END, f'{self.computer_guess} is too low, or too high, or it is the correct number you are thinking of?\n')

        else:
            self.pn2_text.insert(END, 'Congrats!!!! Computer, you just happen to know which number I am thinking!')

    def pn1_varCheck(self):
        if self.from_num.get() == '' or self.to_num.get() == '':
            messagebox.showwarning('Warning','No From or To bound.')

    def pn2_varCheck(self):
        if self.upper_bound.get() == '':
            messagebox.showwarning('Warning','No Upper bound.')


def main():
    app = Tk()
    MainFrame(app)
    # app.state('zoomed') # maximize GUI
    app.mainloop()


if __name__ == '__main__':
    main()
